---
abstract: 'Cisco IOS Config Diff Utility'
author:
  - 'Oliver Gorwits <oliver@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-iosdiff
requires:
  Algorithm::Diff: 0
  Exporter: 0
  File::Slurp: 0
  File::Temp: 0
  List::Util: 0
  Net::DNS: 0
  Regexp::Common: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=App-iosdiff
  homepage: https://github.com/ollyg/App-iosdiff/wiki
  repository: git://github.com/ollyg/App-iosdiff.git
version: 1.112140
